from __future__ import annotations

from typing import Protocol

from src.domain.entity import (
    AgentRunRecord,
    AnalysisTask,
    NotificationChannel,
    NotificationRecord,
    Portfolio,
    ReportArchive,
    ScheduledJob,
    ToolCallRecord,
    TradeJournal,
    User,
    WatchItem,
)


class UserRepository(Protocol):
    def save(self, user: User) -> User: ...
    def get(self, user_id: str) -> User | None: ...


class PortfolioRepository(Protocol):
    def save(self, portfolio: Portfolio) -> Portfolio: ...
    def get(self, portfolio_id: str) -> Portfolio | None: ...
    def list_by_user(self, user_id: str) -> list[Portfolio]: ...


class WatchRepository(Protocol):
    def save(self, item: WatchItem) -> WatchItem: ...
    def list_by_user(self, user_id: str) -> list[WatchItem]: ...
    def delete(self, watch_id: str) -> bool: ...


class TradeJournalRepository(Protocol):
    def save(self, journal: TradeJournal) -> TradeJournal: ...
    def list_by_user(self, user_id: str, symbol: str | None = None) -> list[TradeJournal]: ...


class AnalysisTaskRepository(Protocol):
    def save(self, task: AnalysisTask) -> AnalysisTask: ...
    def get(self, task_id: str) -> AnalysisTask | None: ...
    def list_by_user(self, user_id: str) -> list[AnalysisTask]: ...
    def list_all(self) -> list[AnalysisTask]: ...


class AgentRunRepository(Protocol):
    def save(self, record: AgentRunRecord) -> AgentRunRecord: ...
    def list_by_task(self, task_id: str) -> list[AgentRunRecord]: ...


class ToolCallRepository(Protocol):
    def save(self, record: ToolCallRecord) -> ToolCallRecord: ...
    def list_by_task(self, task_id: str) -> list[ToolCallRecord]: ...


class ReportRepository(Protocol):
    def save(self, report: ReportArchive) -> ReportArchive: ...
    def get_by_task(self, task_id: str) -> ReportArchive | None: ...


class NotificationRepository(Protocol):
    def save_channel(self, channel: NotificationChannel) -> NotificationChannel: ...
    def get_channel(self, channel_id: str) -> NotificationChannel | None: ...
    def list_channels(self, user_id: str) -> list[NotificationChannel]: ...
    def save_record(self, record: NotificationRecord) -> NotificationRecord: ...
    def get_record(self, record_id: str) -> NotificationRecord | None: ...
    def list_records(self, user_id: str) -> list[NotificationRecord]: ...
    def list_records_by_status(self, status: str) -> list[NotificationRecord]: ...


class ScheduledJobRepository(Protocol):
    def save(self, job: ScheduledJob) -> ScheduledJob: ...
    def get(self, job_id: str) -> ScheduledJob | None: ...
    def list_by_user(self, user_id: str) -> list[ScheduledJob]: ...
    def list_enabled(self, user_id: str | None = None) -> list[ScheduledJob]: ...
    def delete(self, job_id: str) -> bool: ...
